package net.java.games.input;

public static class Key extends Identifier
{
    public static final Key VOID;
    public static final Key ESCAPE;
    public static final Key _1;
    public static final Key _2;
    public static final Key _3;
    public static final Key _4;
    public static final Key _5;
    public static final Key _6;
    public static final Key _7;
    public static final Key _8;
    public static final Key _9;
    public static final Key _0;
    public static final Key MINUS;
    public static final Key EQUALS;
    public static final Key BACK;
    public static final Key TAB;
    public static final Key Q;
    public static final Key W;
    public static final Key E;
    public static final Key R;
    public static final Key T;
    public static final Key Y;
    public static final Key U;
    public static final Key I;
    public static final Key O;
    public static final Key P;
    public static final Key LBRACKET;
    public static final Key RBRACKET;
    public static final Key RETURN;
    public static final Key LCONTROL;
    public static final Key A;
    public static final Key S;
    public static final Key D;
    public static final Key F;
    public static final Key G;
    public static final Key H;
    public static final Key J;
    public static final Key K;
    public static final Key L;
    public static final Key SEMICOLON;
    public static final Key APOSTROPHE;
    public static final Key GRAVE;
    public static final Key LSHIFT;
    public static final Key BACKSLASH;
    public static final Key Z;
    public static final Key X;
    public static final Key C;
    public static final Key V;
    public static final Key B;
    public static final Key N;
    public static final Key M;
    public static final Key COMMA;
    public static final Key PERIOD;
    public static final Key SLASH;
    public static final Key RSHIFT;
    public static final Key MULTIPLY;
    public static final Key LALT;
    public static final Key SPACE;
    public static final Key CAPITAL;
    public static final Key F1;
    public static final Key F2;
    public static final Key F3;
    public static final Key F4;
    public static final Key F5;
    public static final Key F6;
    public static final Key F7;
    public static final Key F8;
    public static final Key F9;
    public static final Key F10;
    public static final Key NUMLOCK;
    public static final Key SCROLL;
    public static final Key NUMPAD7;
    public static final Key NUMPAD8;
    public static final Key NUMPAD9;
    public static final Key SUBTRACT;
    public static final Key NUMPAD4;
    public static final Key NUMPAD5;
    public static final Key NUMPAD6;
    public static final Key ADD;
    public static final Key NUMPAD1;
    public static final Key NUMPAD2;
    public static final Key NUMPAD3;
    public static final Key NUMPAD0;
    public static final Key DECIMAL;
    public static final Key F11;
    public static final Key F12;
    public static final Key F13;
    public static final Key F14;
    public static final Key F15;
    public static final Key KANA;
    public static final Key CONVERT;
    public static final Key NOCONVERT;
    public static final Key YEN;
    public static final Key NUMPADEQUAL;
    public static final Key CIRCUMFLEX;
    public static final Key AT;
    public static final Key COLON;
    public static final Key UNDERLINE;
    public static final Key KANJI;
    public static final Key STOP;
    public static final Key AX;
    public static final Key UNLABELED;
    public static final Key NUMPADENTER;
    public static final Key RCONTROL;
    public static final Key NUMPADCOMMA;
    public static final Key DIVIDE;
    public static final Key SYSRQ;
    public static final Key RALT;
    public static final Key PAUSE;
    public static final Key HOME;
    public static final Key UP;
    public static final Key PAGEUP;
    public static final Key LEFT;
    public static final Key RIGHT;
    public static final Key END;
    public static final Key DOWN;
    public static final Key PAGEDOWN;
    public static final Key INSERT;
    public static final Key DELETE;
    public static final Key LWIN;
    public static final Key RWIN;
    public static final Key APPS;
    public static final Key POWER;
    public static final Key SLEEP;
    public static final Key UNKNOWN;
    
    protected Key(final String name) {
        super(name);
    }
    
    static {
        VOID = new Key("Void");
        ESCAPE = new Key("Escape");
        _1 = new Key("1");
        _2 = new Key("2");
        _3 = new Key("3");
        _4 = new Key("4");
        _5 = new Key("5");
        _6 = new Key("6");
        _7 = new Key("7");
        _8 = new Key("8");
        _9 = new Key("9");
        _0 = new Key("0");
        MINUS = new Key("-");
        EQUALS = new Key("=");
        BACK = new Key("Back");
        TAB = new Key("Tab");
        Q = new Key("Q");
        W = new Key("W");
        E = new Key("E");
        R = new Key("R");
        T = new Key("T");
        Y = new Key("Y");
        U = new Key("U");
        I = new Key("I");
        O = new Key("O");
        P = new Key("P");
        LBRACKET = new Key("[");
        RBRACKET = new Key("]");
        RETURN = new Key("Return");
        LCONTROL = new Key("Left Control");
        A = new Key("A");
        S = new Key("S");
        D = new Key("D");
        F = new Key("F");
        G = new Key("G");
        H = new Key("H");
        J = new Key("J");
        K = new Key("K");
        L = new Key("L");
        SEMICOLON = new Key(";");
        APOSTROPHE = new Key("'");
        GRAVE = new Key("~");
        LSHIFT = new Key("Left Shift");
        BACKSLASH = new Key("\\");
        Z = new Key("Z");
        X = new Key("X");
        C = new Key("C");
        V = new Key("V");
        B = new Key("B");
        N = new Key("N");
        M = new Key("M");
        COMMA = new Key(",");
        PERIOD = new Key(".");
        SLASH = new Key("/");
        RSHIFT = new Key("Right Shift");
        MULTIPLY = new Key("Multiply");
        LALT = new Key("Left Alt");
        SPACE = new Key(" ");
        CAPITAL = new Key("Caps Lock");
        F1 = new Key("F1");
        F2 = new Key("F2");
        F3 = new Key("F3");
        F4 = new Key("F4");
        F5 = new Key("F5");
        F6 = new Key("F6");
        F7 = new Key("F7");
        F8 = new Key("F8");
        F9 = new Key("F9");
        F10 = new Key("F10");
        NUMLOCK = new Key("Num Lock");
        SCROLL = new Key("Scroll Lock");
        NUMPAD7 = new Key("Num 7");
        NUMPAD8 = new Key("Num 8");
        NUMPAD9 = new Key("Num 9");
        SUBTRACT = new Key("Num -");
        NUMPAD4 = new Key("Num 4");
        NUMPAD5 = new Key("Num 5");
        NUMPAD6 = new Key("Num 6");
        ADD = new Key("Num +");
        NUMPAD1 = new Key("Num 1");
        NUMPAD2 = new Key("Num 2");
        NUMPAD3 = new Key("Num 3");
        NUMPAD0 = new Key("Num 0");
        DECIMAL = new Key("Num .");
        F11 = new Key("F11");
        F12 = new Key("F12");
        F13 = new Key("F13");
        F14 = new Key("F14");
        F15 = new Key("F15");
        KANA = new Key("Kana");
        CONVERT = new Key("Convert");
        NOCONVERT = new Key("Noconvert");
        YEN = new Key("Yen");
        NUMPADEQUAL = new Key("Num =");
        CIRCUMFLEX = new Key("Circumflex");
        AT = new Key("At");
        COLON = new Key("Colon");
        UNDERLINE = new Key("Underline");
        KANJI = new Key("Kanji");
        STOP = new Key("Stop");
        AX = new Key("Ax");
        UNLABELED = new Key("Unlabeled");
        NUMPADENTER = new Key("Num Enter");
        RCONTROL = new Key("Right Control");
        NUMPADCOMMA = new Key("Num ,");
        DIVIDE = new Key("Num /");
        SYSRQ = new Key("SysRq");
        RALT = new Key("Right Alt");
        PAUSE = new Key("Pause");
        HOME = new Key("Home");
        UP = new Key("Up");
        PAGEUP = new Key("Pg Up");
        LEFT = new Key("Left");
        RIGHT = new Key("Right");
        END = new Key("End");
        DOWN = new Key("Down");
        PAGEDOWN = new Key("Pg Down");
        INSERT = new Key("Insert");
        DELETE = new Key("Delete");
        LWIN = new Key("Left Windows");
        RWIN = new Key("Right Windows");
        APPS = new Key("Apps");
        POWER = new Key("Power");
        SLEEP = new Key("Sleep");
        UNKNOWN = new Key("Unknown");
    }
}
