package net.java.games.input;

public static class Button extends Identifier
{
    public static final Button _0;
    public static final Button _1;
    public static final Button _2;
    public static final Button _3;
    public static final Button _4;
    public static final Button _5;
    public static final Button _6;
    public static final Button _7;
    public static final Button _8;
    public static final Button _9;
    public static final Button _10;
    public static final Button _11;
    public static final Button _12;
    public static final Button _13;
    public static final Button _14;
    public static final Button _15;
    public static final Button _16;
    public static final Button _17;
    public static final Button _18;
    public static final Button _19;
    public static final Button _20;
    public static final Button _21;
    public static final Button _22;
    public static final Button _23;
    public static final Button _24;
    public static final Button _25;
    public static final Button _26;
    public static final Button _27;
    public static final Button _28;
    public static final Button _29;
    public static final Button _30;
    public static final Button _31;
    public static final Button TRIGGER;
    public static final Button THUMB;
    public static final Button THUMB2;
    public static final Button TOP;
    public static final Button TOP2;
    public static final Button PINKIE;
    public static final Button BASE;
    public static final Button BASE2;
    public static final Button BASE3;
    public static final Button BASE4;
    public static final Button BASE5;
    public static final Button BASE6;
    public static final Button DEAD;
    public static final Button A;
    public static final Button B;
    public static final Button C;
    public static final Button X;
    public static final Button Y;
    public static final Button Z;
    public static final Button LEFT_THUMB;
    public static final Button RIGHT_THUMB;
    public static final Button LEFT_THUMB2;
    public static final Button RIGHT_THUMB2;
    public static final Button SELECT;
    public static final Button MODE;
    public static final Button LEFT_THUMB3;
    public static final Button RIGHT_THUMB3;
    public static final Button TOOL_PEN;
    public static final Button TOOL_RUBBER;
    public static final Button TOOL_BRUSH;
    public static final Button TOOL_PENCIL;
    public static final Button TOOL_AIRBRUSH;
    public static final Button TOOL_FINGER;
    public static final Button TOOL_MOUSE;
    public static final Button TOOL_LENS;
    public static final Button TOUCH;
    public static final Button STYLUS;
    public static final Button STYLUS2;
    public static final Button UNKNOWN;
    public static final Button BACK;
    public static final Button EXTRA;
    public static final Button FORWARD;
    public static final Button LEFT;
    public static final Button MIDDLE;
    public static final Button RIGHT;
    public static final Button SIDE;
    
    public Button(final String name) {
        super(name);
    }
    
    static {
        _0 = new Button("0");
        _1 = new Button("1");
        _2 = new Button("2");
        _3 = new Button("3");
        _4 = new Button("4");
        _5 = new Button("5");
        _6 = new Button("6");
        _7 = new Button("7");
        _8 = new Button("8");
        _9 = new Button("9");
        _10 = new Button("10");
        _11 = new Button("11");
        _12 = new Button("12");
        _13 = new Button("13");
        _14 = new Button("14");
        _15 = new Button("15");
        _16 = new Button("16");
        _17 = new Button("17");
        _18 = new Button("18");
        _19 = new Button("19");
        _20 = new Button("20");
        _21 = new Button("21");
        _22 = new Button("22");
        _23 = new Button("23");
        _24 = new Button("24");
        _25 = new Button("25");
        _26 = new Button("26");
        _27 = new Button("27");
        _28 = new Button("28");
        _29 = new Button("29");
        _30 = new Button("30");
        _31 = new Button("31");
        TRIGGER = new Button("Trigger");
        THUMB = new Button("Thumb");
        THUMB2 = new Button("Thumb 2");
        TOP = new Button("Top");
        TOP2 = new Button("Top 2");
        PINKIE = new Button("Pinkie");
        BASE = new Button("Base");
        BASE2 = new Button("Base 2");
        BASE3 = new Button("Base 3");
        BASE4 = new Button("Base 4");
        BASE5 = new Button("Base 5");
        BASE6 = new Button("Base 6");
        DEAD = new Button("Dead");
        A = new Button("A");
        B = new Button("B");
        C = new Button("C");
        X = new Button("X");
        Y = new Button("Y");
        Z = new Button("Z");
        LEFT_THUMB = new Button("Left Thumb");
        RIGHT_THUMB = new Button("Right Thumb");
        LEFT_THUMB2 = new Button("Left Thumb 2");
        RIGHT_THUMB2 = new Button("Right Thumb 2");
        SELECT = new Button("Select");
        MODE = new Button("Mode");
        LEFT_THUMB3 = new Button("Left Thumb 3");
        RIGHT_THUMB3 = new Button("Right Thumb 3");
        TOOL_PEN = new Button("Pen");
        TOOL_RUBBER = new Button("Rubber");
        TOOL_BRUSH = new Button("Brush");
        TOOL_PENCIL = new Button("Pencil");
        TOOL_AIRBRUSH = new Button("Airbrush");
        TOOL_FINGER = new Button("Finger");
        TOOL_MOUSE = new Button("Mouse");
        TOOL_LENS = new Button("Lens");
        TOUCH = new Button("Touch");
        STYLUS = new Button("Stylus");
        STYLUS2 = new Button("Stylus 2");
        UNKNOWN = new Button("Unknown");
        BACK = new Button("Back");
        EXTRA = new Button("Extra");
        FORWARD = new Button("Forward");
        LEFT = new Button("Left");
        MIDDLE = new Button("Middle");
        RIGHT = new Button("Right");
        SIDE = new Button("Side");
    }
}
