/*
 * Decompiled with CFR 0.152.
 */
package de.gerrygames.viarewind.protocol.protocol1_8to1_9.sound;

import java.util.HashMap;

public class SoundRemapper {
    private static final HashMap<Integer, String> sounds1_9 = new HashMap();
    private static final HashMap<String, String> sound1_9to1_8 = new HashMap();
    private static int id;

    private static void register1_9Sound(String sound1_9) {
        sounds1_9.put(id++, sound1_9);
    }

    private static void registerSoundRemapping(String sound1_9, String sound1_8) {
        sound1_9to1_8.put(sound1_9, sound1_8);
    }

    public static String oldNameFromId(int id) {
        String sound1_9 = sounds1_9.get(id);
        if (sound1_9 != null) return SoundRemapper.getOldName(sound1_9);
        return null;
    }

    public static String getOldName(String sound1_9) {
        return sound1_9to1_8.getOrDefault(sound1_9, sound1_9);
    }

    static {
        SoundRemapper.registerSoundRemapping("entity.zombie_horse.ambient", "mob.horse.zombie.idle");
        SoundRemapper.registerSoundRemapping("block.note.snare", "note.snare");
        SoundRemapper.registerSoundRemapping("block.wood_button.click_off", "random.wood_click");
        SoundRemapper.registerSoundRemapping("block.wood_button.click_on", "random.wood_click");
        SoundRemapper.registerSoundRemapping("block.gravel.break", "dig.gravel");
        SoundRemapper.registerSoundRemapping("block.gravel.place", "dig.gravel");
        SoundRemapper.registerSoundRemapping("entity.arrow.hit", "random.bowhit");
        SoundRemapper.registerSoundRemapping("block.tripwire.detach", "random.bowhit");
        SoundRemapper.registerSoundRemapping("entity.splash_potion.break", "dig.glass");
        SoundRemapper.registerSoundRemapping("block.glass.break", "dig.glass");
        SoundRemapper.registerSoundRemapping("entity.zombie.ambient", "mob.zombie.say");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.ambient", "mob.zombie.say");
        SoundRemapper.registerSoundRemapping("entity.pig.death", "mob.pig.death");
        SoundRemapper.registerSoundRemapping("entity.mule.hurt", "mob.horse.donkey.hit");
        SoundRemapper.registerSoundRemapping("entity.donkey.hurt", "mob.horse.donkey.hit");
        SoundRemapper.registerSoundRemapping("entity.endermen.ambient", "mob.endermen.idle");
        SoundRemapper.registerSoundRemapping("block.portal.ambient", "portal.portal");
        SoundRemapper.registerSoundRemapping("entity.generic.burn", "random.fizz");
        SoundRemapper.registerSoundRemapping("block.fire.extinguish", "random.fizz");
        SoundRemapper.registerSoundRemapping("block.redstone_torch.burnout", "random.fizz");
        SoundRemapper.registerSoundRemapping("block.lava.extinguish", "random.fizz");
        SoundRemapper.registerSoundRemapping("entity.generic.extinguish_fire", "random.fizz");
        SoundRemapper.registerSoundRemapping("block.note.harp", "note.harp");
        SoundRemapper.registerSoundRemapping("block.snow.hit", "step.snow");
        SoundRemapper.registerSoundRemapping("block.snow.fall", "step.snow");
        SoundRemapper.registerSoundRemapping("block.snow.step", "step.snow");
        SoundRemapper.registerSoundRemapping("entity.arrow.hit_player", "random.successful_hit");
        SoundRemapper.registerSoundRemapping("entity.zombie_pig.hurt", "mob.zombiepig.zpighurt");
        SoundRemapper.registerSoundRemapping("entity.wolf.howl", "mob.wolf.howl");
        SoundRemapper.registerSoundRemapping("entity.firework.launch", "fireworks.launch");
        SoundRemapper.registerSoundRemapping("entity.cow.hurt", "mob.cow.hurt");
        SoundRemapper.registerSoundRemapping("entity.cow.death", "mob.cow.hurt");
        SoundRemapper.registerSoundRemapping("entity.firework.large_blast", "fireworks.largeBlast");
        SoundRemapper.registerSoundRemapping("entity.blaze.hurt", "mob.blaze.hit");
        SoundRemapper.registerSoundRemapping("entity.villager.death", "mob.villager.death");
        SoundRemapper.registerSoundRemapping("entity.blaze.death", "mob.blaze.death");
        SoundRemapper.registerSoundRemapping("entity.zombie_horse.death", "mob.horse.zombie.death");
        SoundRemapper.registerSoundRemapping("entity.silverfish.death", "mob.silverfish.kill");
        SoundRemapper.registerSoundRemapping("entity.endermite.death", "mob.silverfish.kill");
        SoundRemapper.registerSoundRemapping("record.ward", "records.ward");
        SoundRemapper.registerSoundRemapping("entity.wolf.pant", "mob.wolf.panting");
        SoundRemapper.registerSoundRemapping("block.metal.break", "dig.stone");
        SoundRemapper.registerSoundRemapping("block.metal.place", "dig.stone");
        SoundRemapper.registerSoundRemapping("entity.armorstand.place", "dig.stone");
        SoundRemapper.registerSoundRemapping("block.stone.break", "dig.stone");
        SoundRemapper.registerSoundRemapping("block.stone.place", "dig.stone");
        SoundRemapper.registerSoundRemapping("block.anvil.break", "dig.stone");
        SoundRemapper.registerSoundRemapping("block.glass.place", "dig.stone");
        SoundRemapper.registerSoundRemapping("entity.endermen.stare", "mob.endermen.stare");
        SoundRemapper.registerSoundRemapping("entity.small_magmacube.hurt", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("block.slime.fall", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("entity.small_slime.death", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("block.slime.step", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("entity.small_magmacube.death", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("entity.small_slime.hurt", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("block.slime.hit", "mob.slime.small");
        SoundRemapper.registerSoundRemapping("music.nether", "music.game.nether");
        SoundRemapper.registerSoundRemapping("entity.ghast.death", "mob.ghast.death");
        SoundRemapper.registerSoundRemapping("entity.guardian.attack", "mob.guardian.attack");
        SoundRemapper.registerSoundRemapping("block.dispenser.fail", "random.click");
        SoundRemapper.registerSoundRemapping("block.comparator.click", "random.click");
        SoundRemapper.registerSoundRemapping("block.stone_button.click_on", "random.click");
        SoundRemapper.registerSoundRemapping("block.stone_button.click_off", "random.click");
        SoundRemapper.registerSoundRemapping("block.tripwire.click_on", "random.click");
        SoundRemapper.registerSoundRemapping("block.dispenser.dispense", "random.click");
        SoundRemapper.registerSoundRemapping("ui.button.click", "random.click");
        SoundRemapper.registerSoundRemapping("block.lever.click", "random.click");
        SoundRemapper.registerSoundRemapping("block.tripwire.attach", "random.click");
        SoundRemapper.registerSoundRemapping("block.stone_pressureplate.click_on", "random.click");
        SoundRemapper.registerSoundRemapping("block.wood_pressureplate.click_off", "random.click");
        SoundRemapper.registerSoundRemapping("block.stone_pressureplate.click_off", "random.click");
        SoundRemapper.registerSoundRemapping("block.metal_pressureplate.click_off", "random.click");
        SoundRemapper.registerSoundRemapping("block.tripwire.click_off", "random.click");
        SoundRemapper.registerSoundRemapping("block.metal_pressureplate.click_on", "random.click");
        SoundRemapper.registerSoundRemapping("block.wood_pressureplate.click_on", "random.click");
        SoundRemapper.registerSoundRemapping("entity.zombie_pig.ambient", "mob.zombiepig.zpig");
        SoundRemapper.registerSoundRemapping("music.dragon", "music.game.end.dragon");
        SoundRemapper.registerSoundRemapping("entity.firework.twinkle_far", "fireworks.twinkle_far");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.ambient_land", "mob.guardian.land.idle");
        SoundRemapper.registerSoundRemapping("entity.guardian.ambient_land", "mob.guardian.land.idle");
        SoundRemapper.registerSoundRemapping("block.grass.break", "dig.grass");
        SoundRemapper.registerSoundRemapping("block.grass.place", "dig.grass");
        SoundRemapper.registerSoundRemapping("entity.skeleton.step", "mob.skeleton.step");
        SoundRemapper.registerSoundRemapping("entity.wither.death", "mob.wither.death");
        SoundRemapper.registerSoundRemapping("entity.wolf.hurt", "mob.wolf.hurt");
        SoundRemapper.registerSoundRemapping("entity.pig.saddle", "mob.horse.leather");
        SoundRemapper.registerSoundRemapping("entity.horse.saddle", "mob.horse.leather");
        SoundRemapper.registerSoundRemapping("entity.bat.loop", "mob.bat.loop");
        SoundRemapper.registerSoundRemapping("entity.ghast.hurt", "mob.ghast.scream");
        SoundRemapper.registerSoundRemapping("entity.creeper.death", "mob.creeper.death");
        SoundRemapper.registerSoundRemapping("entity.horse.gallop", "mob.horse.gallop");
        SoundRemapper.registerSoundRemapping("entity.wither.spawn", "mob.wither.spawn");
        SoundRemapper.registerSoundRemapping("entity.endermen.hurt", "mob.endermen.hit");
        SoundRemapper.registerSoundRemapping("entity.creeper.hurt", "mob.creeper.say");
        SoundRemapper.registerSoundRemapping("entity.horse.step_wood", "mob.horse.wood");
        SoundRemapper.registerSoundRemapping("entity.rabbit.death", "mob.rabbit.death");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.converted", "mob.zombie.unfect");
        SoundRemapper.registerSoundRemapping("block.anvil.use", "random.anvil_use");
        SoundRemapper.registerSoundRemapping("block.enderchest.close", "random.chestclosed");
        SoundRemapper.registerSoundRemapping("entity.mooshroom.shear", "mob.sheep.shear");
        SoundRemapper.registerSoundRemapping("entity.sheep.shear", "mob.sheep.shear");
        SoundRemapper.registerSoundRemapping("entity.item.pickup", "random.pop");
        SoundRemapper.registerSoundRemapping("entity.bat.death", "mob.bat.death");
        SoundRemapper.registerSoundRemapping("block.wood.place", "dig.wood");
        SoundRemapper.registerSoundRemapping("block.wood.break", "dig.wood");
        SoundRemapper.registerSoundRemapping("block.ladder.place", "dig.wood");
        SoundRemapper.registerSoundRemapping("entity.armorstand.fall", "dig.wood");
        SoundRemapper.registerSoundRemapping("block.ladder.break", "dig.wood");
        SoundRemapper.registerSoundRemapping("record.chirp", "records.chirp");
        SoundRemapper.registerSoundRemapping("entity.mule.death", "mob.horse.donkey.death");
        SoundRemapper.registerSoundRemapping("entity.donkey.death", "mob.horse.donkey.death");
        SoundRemapper.registerSoundRemapping("entity.firework.blast", "fireworks.blast");
        SoundRemapper.registerSoundRemapping("entity.zombie_pig.angry", "mob.zombiepig.zpigangry");
        SoundRemapper.registerSoundRemapping("entity.guardian.flop", "mob.guardian.flop");
        SoundRemapper.registerSoundRemapping("entity.villager.yes", "mob.villager.yes");
        SoundRemapper.registerSoundRemapping("entity.ghast.warn", "mob.ghast.charge");
        SoundRemapper.registerSoundRemapping("entity.tnt.primed", "creeper.primed");
        SoundRemapper.registerSoundRemapping("entity.creeper.primed", "creeper.primed");
        SoundRemapper.registerSoundRemapping("block.sand.place", "dig.sand");
        SoundRemapper.registerSoundRemapping("block.sand.break", "dig.sand");
        SoundRemapper.registerSoundRemapping("entity.chicken.ambient", "mob.chicken.say");
        SoundRemapper.registerSoundRemapping("record.13", "records.13");
        SoundRemapper.registerSoundRemapping("record.11", "records.11");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.death", "mob.guardian.elder.death");
        SoundRemapper.registerSoundRemapping("entity.firework.twinkle", "fireworks.twinkle");
        SoundRemapper.registerSoundRemapping("entity.skeleton_horse.death", "mob.horse.skeleton.death");
        SoundRemapper.registerSoundRemapping("weather.rain", "ambient.weather.rain");
        SoundRemapper.registerSoundRemapping("weather.rain.above", "ambient.weather.rain");
        SoundRemapper.registerSoundRemapping("block.portal.trigger", "portal.trigger");
        SoundRemapper.registerSoundRemapping("block.enderchest.open", "random.chestopen");
        SoundRemapper.registerSoundRemapping("entity.horse.land", "mob.horse.land");
        SoundRemapper.registerSoundRemapping("entity.endermite.step", "mob.silverfish.step");
        SoundRemapper.registerSoundRemapping("entity.silverfish.step", "mob.silverfish.step");
        SoundRemapper.registerSoundRemapping("entity.bat.takeoff", "mob.bat.takeoff");
        SoundRemapper.registerSoundRemapping("entity.villager.no", "mob.villager.no");
        SoundRemapper.registerSoundRemapping("entity.irongolem.step", "mob.irongolem.walk");
        SoundRemapper.registerSoundRemapping("block.note.hat", "note.hat");
        SoundRemapper.registerSoundRemapping("entity.zombie.attack_iron_door", "mob.zombie.metal");
        SoundRemapper.registerSoundRemapping("entity.villager.trading", "mob.villager.haggle");
        SoundRemapper.registerSoundRemapping("item.firecharge.use", "mob.ghast.fireball");
        SoundRemapper.registerSoundRemapping("entity.ghast.shoot", "mob.ghast.fireball");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.shoot", "mob.ghast.fireball");
        SoundRemapper.registerSoundRemapping("entity.blaze.shoot", "mob.ghast.fireball");
        SoundRemapper.registerSoundRemapping("music.credits", "music.game.end.credits");
        SoundRemapper.registerSoundRemapping("entity.irongolem.death", "mob.irongolem.death");
        SoundRemapper.registerSoundRemapping("entity.item.break", "random.break");
        SoundRemapper.registerSoundRemapping("item.shield.break", "random.break");
        SoundRemapper.registerSoundRemapping("record.mellohi", "records.mellohi");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.cure", "mob.zombie.remedy");
        SoundRemapper.registerSoundRemapping("entity.enderpearl.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("block.dispenser.launch", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.skeleton.shoot", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.endereye.launch", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.firework.shoot", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.experience_bottle.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.snowman.shoot", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.arrow.shoot", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.egg.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.snowball.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.bobber.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.lingeringpotion.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.splash_potion.throw", "random.bow");
        SoundRemapper.registerSoundRemapping("entity.villager.ambient", "mob.villager.idle");
        SoundRemapper.registerSoundRemapping("block.cloth.hit", "step.cloth");
        SoundRemapper.registerSoundRemapping("block.cloth.step", "step.cloth");
        SoundRemapper.registerSoundRemapping("block.cloth.fall", "step.cloth");
        SoundRemapper.registerSoundRemapping("entity.silverfish.hurt", "mob.silverfish.hit");
        SoundRemapper.registerSoundRemapping("entity.endermite.hurt", "mob.silverfish.hit");
        SoundRemapper.registerSoundRemapping("music.game", "music.game");
        SoundRemapper.registerSoundRemapping("block.lava.ambient", "liquid.lava");
        SoundRemapper.registerSoundRemapping("record.mall", "records.mall");
        SoundRemapper.registerSoundRemapping("entity.blaze.burn", "fire.fire");
        SoundRemapper.registerSoundRemapping("block.fire.ambient", "fire.fire");
        SoundRemapper.registerSoundRemapping("entity.zombie.attack_door_wood", "mob.zombie.wood");
        SoundRemapper.registerSoundRemapping("entity.chicken.step", "mob.chicken.step");
        SoundRemapper.registerSoundRemapping("record.stal", "records.stal");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.hurt_land", "mob.guardian.land.hit");
        SoundRemapper.registerSoundRemapping("entity.guardian.hurt_land", "mob.guardian.land.hit");
        SoundRemapper.registerSoundRemapping("entity.chicken.egg", "mob.chicken.plop");
        SoundRemapper.registerSoundRemapping("entity.donkey.chest", "mob.chicken.plop");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.flap", "mob.enderdragon.wings");
        SoundRemapper.registerSoundRemapping("block.grass.step", "step.grass");
        SoundRemapper.registerSoundRemapping("block.grass.fall", "step.grass");
        SoundRemapper.registerSoundRemapping("block.grass.hit", "step.grass");
        SoundRemapper.registerSoundRemapping("entity.horse.breathe", "mob.horse.breathe");
        SoundRemapper.registerSoundRemapping("entity.mule.ambient", "mob.horse.donkey.idle");
        SoundRemapper.registerSoundRemapping("entity.donkey.ambient", "mob.horse.donkey.idle");
        SoundRemapper.registerSoundRemapping("record.far", "records.far");
        SoundRemapper.registerSoundRemapping("entity.spider.step", "mob.spider.step");
        SoundRemapper.registerSoundRemapping("entity.cow.ambient", "mob.cow.say");
        SoundRemapper.registerSoundRemapping("entity.horse.jump", "mob.horse.jump");
        SoundRemapper.registerSoundRemapping("entity.horse.step", "mob.horse.soft");
        SoundRemapper.registerSoundRemapping("entity.guardian.hurt", "mob.guardian.hit");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.death", "mob.enderdragon.end");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.step", "mob.zombie.step");
        SoundRemapper.registerSoundRemapping("entity.zombie.step", "mob.zombie.step");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.ambient", "mob.enderdragon.growl");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.growl", "mob.enderdragon.growl");
        SoundRemapper.registerSoundRemapping("entity.wolf.shake", "mob.wolf.shake");
        SoundRemapper.registerSoundRemapping("entity.endermen.death", "mob.endermen.death");
        SoundRemapper.registerSoundRemapping("block.anvil.place", "random.anvil_land");
        SoundRemapper.registerSoundRemapping("block.anvil.land", "random.anvil_land");
        SoundRemapper.registerSoundRemapping("entity.minecart.inside", "minecart.inside");
        SoundRemapper.registerSoundRemapping("entity.slime.squish", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("entity.magmacube.hurt", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("entity.magmacube.death", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("block.slime.break", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("block.slime.place", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("entity.slime.jump", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("entity.slime.hurt", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("entity.slime.death", "mob.slime.big");
        SoundRemapper.registerSoundRemapping("block.water.ambient", "liquid.water");
        SoundRemapper.registerSoundRemapping("entity.pig.hurt", "mob.pig.say");
        SoundRemapper.registerSoundRemapping("entity.pig.ambient", "mob.pig.say");
        SoundRemapper.registerSoundRemapping("entity.wither.shoot", "mob.wither.shoot");
        SoundRemapper.registerSoundRemapping("record.blocks", "records.blocks");
        SoundRemapper.registerSoundRemapping("item.firecharge.use", "item.fireCharge.use");
        SoundRemapper.registerSoundRemapping("entity.ghast.shoot", "item.fireCharge.use");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.shoot", "item.fireCharge.use");
        SoundRemapper.registerSoundRemapping("entity.blaze.shoot", "item.fireCharge.use");
        SoundRemapper.registerSoundRemapping("block.sand.hit", "step.sand");
        SoundRemapper.registerSoundRemapping("block.sand.step", "step.sand");
        SoundRemapper.registerSoundRemapping("block.sand.fall", "step.sand");
        SoundRemapper.registerSoundRemapping("music.creative", "music.game.creative");
        SoundRemapper.registerSoundRemapping("entity.irongolem.hurt", "mob.irongolem.hit");
        SoundRemapper.registerSoundRemapping("entity.horse.death", "mob.horse.death");
        SoundRemapper.registerSoundRemapping("entity.bat.hurt", "mob.bat.hurt");
        SoundRemapper.registerSoundRemapping("entity.ghast.scream", "mob.ghast.affectionate_scream");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.ambient", "mob.guardian.elder.idle");
        SoundRemapper.registerSoundRemapping("entity.zombie_pig.death", "mob.zombiepig.zpigdeath");
        SoundRemapper.registerSoundRemapping("entity.lightning.thunder", "ambient.weather.thunder");
        SoundRemapper.registerSoundRemapping("entity.minecart.riding", "minecart.base");
        SoundRemapper.registerSoundRemapping("block.ladder.step", "step.ladder");
        SoundRemapper.registerSoundRemapping("block.ladder.fall", "step.ladder");
        SoundRemapper.registerSoundRemapping("block.ladder.hit", "step.ladder");
        SoundRemapper.registerSoundRemapping("entity.donkey.angry", "mob.horse.donkey.angry");
        SoundRemapper.registerSoundRemapping("ambient.cave", "ambient.cave.cave");
        SoundRemapper.registerSoundRemapping("record.wait", "records.wait");
        SoundRemapper.registerSoundRemapping("entity.firework.blast_far", "fireworks.blast_far");
        SoundRemapper.registerSoundRemapping("entity.generic.drink", "random.drink");
        SoundRemapper.registerSoundRemapping("music.menu", "music.menu");
        SoundRemapper.registerSoundRemapping("entity.cat.hiss", "mob.cat.hiss");
        SoundRemapper.registerSoundRemapping("block.note.basedrum", "note.bd");
        SoundRemapper.registerSoundRemapping("entity.spider.ambient", "mob.spider.say");
        SoundRemapper.registerSoundRemapping("entity.spider.hurt", "mob.spider.say");
        SoundRemapper.registerSoundRemapping("block.stone.fall", "step.stone");
        SoundRemapper.registerSoundRemapping("block.anvil.fall", "step.stone");
        SoundRemapper.registerSoundRemapping("block.metal.step", "step.stone");
        SoundRemapper.registerSoundRemapping("block.stone.hit", "step.stone");
        SoundRemapper.registerSoundRemapping("block.glass.fall", "step.stone");
        SoundRemapper.registerSoundRemapping("block.stone.step", "step.stone");
        SoundRemapper.registerSoundRemapping("block.anvil.step", "step.stone");
        SoundRemapper.registerSoundRemapping("block.metal.hit", "step.stone");
        SoundRemapper.registerSoundRemapping("block.glass.step", "step.stone");
        SoundRemapper.registerSoundRemapping("block.metal.fall", "step.stone");
        SoundRemapper.registerSoundRemapping("block.glass.hit", "step.stone");
        SoundRemapper.registerSoundRemapping("block.anvil.hit", "step.stone");
        SoundRemapper.registerSoundRemapping("entity.player.levelup", "random.levelup");
        SoundRemapper.registerSoundRemapping("block.lava.pop", "liquid.lavapop");
        SoundRemapper.registerSoundRemapping("entity.sheep.hurt", "mob.sheep.say");
        SoundRemapper.registerSoundRemapping("entity.sheep.death", "mob.sheep.say");
        SoundRemapper.registerSoundRemapping("entity.sheep.ambient", "mob.sheep.say");
        SoundRemapper.registerSoundRemapping("entity.skeleton.ambient", "mob.skeleton.say");
        SoundRemapper.registerSoundRemapping("entity.blaze.ambient", "mob.blaze.breathe");
        SoundRemapper.registerSoundRemapping("entity.bat.ambient", "mob.bat.idle");
        SoundRemapper.registerSoundRemapping("entity.magmacube.squish", "mob.magmacube.big");
        SoundRemapper.registerSoundRemapping("entity.horse.ambient", "mob.horse.idle");
        SoundRemapper.registerSoundRemapping("entity.zombie_horse.hurt", "mob.horse.zombie.hit");
        SoundRemapper.registerSoundRemapping("entity.irongolem.attack", "mob.irongolem.throw");
        SoundRemapper.registerSoundRemapping("block.cloth.break", "dig.cloth");
        SoundRemapper.registerSoundRemapping("block.cloth.place", "dig.cloth");
        SoundRemapper.registerSoundRemapping("block.gravel.fall", "step.gravel");
        SoundRemapper.registerSoundRemapping("block.gravel.step", "step.gravel");
        SoundRemapper.registerSoundRemapping("block.gravel.hit", "step.gravel");
        SoundRemapper.registerSoundRemapping("entity.endermite.ambient", "mob.silverfish.say");
        SoundRemapper.registerSoundRemapping("entity.silverfish.ambient", "mob.silverfish.say");
        SoundRemapper.registerSoundRemapping("entity.cat.purr", "mob.cat.purr");
        SoundRemapper.registerSoundRemapping("entity.zombie.infect", "mob.zombie.infect");
        SoundRemapper.registerSoundRemapping("entity.generic.eat", "random.eat");
        SoundRemapper.registerSoundRemapping("entity.wolf.ambient", "mob.wolf.bark");
        SoundRemapper.registerSoundRemapping("entity.tnt.primed", "game.tnt.primed");
        SoundRemapper.registerSoundRemapping("entity.creeper.primed", "game.tnt.primed");
        SoundRemapper.registerSoundRemapping("entity.sheep.step", "mob.sheep.step");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.death", "mob.zombie.death");
        SoundRemapper.registerSoundRemapping("entity.zombie.death", "mob.zombie.death");
        SoundRemapper.registerSoundRemapping("entity.shulker.teleport", "mob.endermen.portal");
        SoundRemapper.registerSoundRemapping("item.chorus_fruit.teleport", "mob.endermen.portal");
        SoundRemapper.registerSoundRemapping("entity.endermen.teleport", "mob.endermen.portal");
        SoundRemapper.registerSoundRemapping("entity.horse.angry", "mob.horse.angry");
        SoundRemapper.registerSoundRemapping("entity.wolf.growl", "mob.wolf.growl");
        SoundRemapper.registerSoundRemapping("block.snow.break", "dig.snow");
        SoundRemapper.registerSoundRemapping("block.snow.place", "dig.snow");
        SoundRemapper.registerSoundRemapping("block.piston.extend", "tile.piston.out");
        SoundRemapper.registerSoundRemapping("entity.player.burp", "random.burp");
        SoundRemapper.registerSoundRemapping("entity.cow.step", "mob.cow.step");
        SoundRemapper.registerSoundRemapping("entity.wither.hurt", "mob.wither.hurt");
        SoundRemapper.registerSoundRemapping("entity.guardian.death_land", "mob.guardian.land.death");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.death_land", "mob.guardian.land.death");
        SoundRemapper.registerSoundRemapping("music.end", "music.game.end");
        SoundRemapper.registerSoundRemapping("entity.chicken.hurt", "mob.chicken.hurt");
        SoundRemapper.registerSoundRemapping("entity.chicken.death", "mob.chicken.hurt");
        SoundRemapper.registerSoundRemapping("entity.wolf.step", "mob.wolf.step");
        SoundRemapper.registerSoundRemapping("entity.wolf.death", "mob.wolf.death");
        SoundRemapper.registerSoundRemapping("entity.wolf.whine", "mob.wolf.whine");
        SoundRemapper.registerSoundRemapping("block.note.pling", "note.pling");
        SoundRemapper.registerSoundRemapping("entity.rabbit.hurt", "mob.rabbit.hurt");
        SoundRemapper.registerSoundRemapping("entity.cat.purreow", "mob.cat.purreow");
        SoundRemapper.registerSoundRemapping("entity.firework.large_blast_far", "fireworks.largeBlast_far");
        SoundRemapper.registerSoundRemapping("entity.skeleton.hurt", "mob.skeleton.hurt");
        SoundRemapper.registerSoundRemapping("entity.spider.death", "mob.spider.death");
        SoundRemapper.registerSoundRemapping("block.anvil.destroy", "random.anvil_break");
        SoundRemapper.registerSoundRemapping("record.cat", "records.cat");
        SoundRemapper.registerSoundRemapping("entity.wither.ambient", "mob.wither.idle");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.hurt", "mob.guardian.elder.hit");
        SoundRemapper.registerSoundRemapping("entity.endermen.scream", "mob.endermen.scream");
        SoundRemapper.registerSoundRemapping("entity.cat.death", "mob.cat.hitt");
        SoundRemapper.registerSoundRemapping("entity.cat.hurt", "mob.cat.hitt");
        SoundRemapper.registerSoundRemapping("entity.small_magmacube.squish", "mob.magmacube.small");
        SoundRemapper.registerSoundRemapping("item.flintandsteel.use", "fire.ignite");
        SoundRemapper.registerSoundRemapping("entity.enderdragon.hurt", "mob.enderdragon.hit");
        SoundRemapper.registerSoundRemapping("entity.zombie.hurt", "mob.zombie.hurt");
        SoundRemapper.registerSoundRemapping("entity.zombie_villager.hurt", "mob.zombie.hurt");
        SoundRemapper.registerSoundRemapping("entity.enderdragon_fireball.explode", "random.explode");
        SoundRemapper.registerSoundRemapping("entity.generic.explode", "random.explode");
        SoundRemapper.registerSoundRemapping("entity.lightning.impact", "random.explode");
        SoundRemapper.registerSoundRemapping("block.end_gateway.spawn", "random.explode");
        SoundRemapper.registerSoundRemapping("entity.slime.attack", "mob.slime.attack");
        SoundRemapper.registerSoundRemapping("entity.magmacube.jump", "mob.magmacube.jump");
        SoundRemapper.registerSoundRemapping("entity.bobber.splash", "random.splash");
        SoundRemapper.registerSoundRemapping("entity.skeleton_horse.hurt", "mob.horse.skeleton.hit");
        SoundRemapper.registerSoundRemapping("entity.rabbit.jump", "mob.rabbit.hop");
        SoundRemapper.registerSoundRemapping("entity.ghast.ambient", "mob.ghast.moan");
        SoundRemapper.registerSoundRemapping("entity.elder_guardian.curse", "mob.guardian.curse");
        SoundRemapper.registerSoundRemapping("entity.splash_potion.break", "game.potion.smash");
        SoundRemapper.registerSoundRemapping("block.glass.break", "game.potion.smash");
        SoundRemapper.registerSoundRemapping("block.note.bass", "note.bassattack");
        SoundRemapper.registerSoundRemapping("block.dispenser.fail", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.comparator.click", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.stone_button.click_on", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.stone_button.click_off", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.tripwire.click_on", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.dispenser.dispense", "gui.button.press");
        SoundRemapper.registerSoundRemapping("ui.button.click", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.lever.click", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.tripwire.attach", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.stone_pressureplate.click_on", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.wood_pressureplate.click_off", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.stone_pressureplate.click_off", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.metal_pressureplate.click_off", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.tripwire.click_off", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.metal_pressureplate.click_on", "gui.button.press");
        SoundRemapper.registerSoundRemapping("block.wood_pressureplate.click_on", "gui.button.press");
        SoundRemapper.registerSoundRemapping("entity.experience_orb.touch", "random.orb");
        SoundRemapper.registerSoundRemapping("entity.experience_orb.pickup", "random.orb");
        SoundRemapper.registerSoundRemapping("entity.wither.break_block", "mob.zombie.woodbreak");
        SoundRemapper.registerSoundRemapping("entity.zombie.break_door_wood", "mob.zombie.woodbreak");
        SoundRemapper.registerSoundRemapping("entity.horse.armor", "mob.horse.armor");
        SoundRemapper.registerSoundRemapping("entity.rabbit.ambient", "mob.rabbit.idle");
        SoundRemapper.registerSoundRemapping("block.piston.contract", "tile.piston.in");
        SoundRemapper.registerSoundRemapping("entity.cat.ambient", "mob.cat.meow");
        SoundRemapper.registerSoundRemapping("entity.pig.step", "mob.pig.step");
        SoundRemapper.registerSoundRemapping("record.strad", "records.strad");
        SoundRemapper.registerSoundRemapping("block.wood.hit", "step.wood");
        SoundRemapper.registerSoundRemapping("block.wood.fall", "step.wood");
        SoundRemapper.registerSoundRemapping("block.wood.step", "step.wood");
        SoundRemapper.registerSoundRemapping("block.portal.travel", "portal.travel");
        SoundRemapper.registerSoundRemapping("entity.guardian.death", "mob.guardian.death");
        SoundRemapper.registerSoundRemapping("entity.skeleton.death", "mob.skeleton.death");
        SoundRemapper.registerSoundRemapping("entity.horse.hurt", "mob.horse.hit");
        SoundRemapper.registerSoundRemapping("entity.villager.hurt", "mob.villager.hit");
        SoundRemapper.registerSoundRemapping("entity.skeleton_horse.ambient", "mob.horse.skeleton.idle");
        SoundRemapper.registerSoundRemapping("block.chest.open", "random.chestopen");
        SoundRemapper.registerSoundRemapping("block.chest.close", "random.chestclosed");
        SoundRemapper.registerSoundRemapping("entity.player.hurt_on_fire", "game.player.hurt");
        SoundRemapper.registerSoundRemapping("entity.player.hurt_drown", "game.player.hurt");
        SoundRemapper.registerSoundRemapping("entity.generic.swim", "game.neutral.swim");
        SoundRemapper.registerSoundRemapping("entity.hostile.swim", "game.hostile.swim");
        SoundRemapper.registerSoundRemapping("entity.player.swim", "game.player.swim");
        SoundRemapper.registerSoundRemapping("entity.player.splash", "game.player.swim.splash");
        SoundRemapper.registerSoundRemapping("entity.hostile.splash", "game.hostile.swim.splash");
        SoundRemapper.registerSoundRemapping("entity.generic.splash", "game.neutral.swim.splash");
        SoundRemapper.registerSoundRemapping("entity.generic.death", "game.neutral.die");
        SoundRemapper.registerSoundRemapping("entity.hostile.hurt", "game.hostile.hurt");
        SoundRemapper.registerSoundRemapping("entity.player.hurt", "game.player.hurt");
        SoundRemapper.registerSoundRemapping("entity.hostile.death", "game.hostile.die");
        SoundRemapper.registerSoundRemapping("entity.generic.hurt", "game.neutral.hurt");
        SoundRemapper.registerSoundRemapping("entity.player.death", "game.player.die");
        SoundRemapper.registerSoundRemapping("entity.player.big_fall", "game.player.hurt.fall.big");
        SoundRemapper.registerSoundRemapping("entity.generic.big_fall", "game.neutral.hurt.fall.big");
        SoundRemapper.registerSoundRemapping("entity.hostile.big_fall", "game.hostile.hurt.fall.big");
        SoundRemapper.registerSoundRemapping("entity.hostile.small_fall", "game.hostile.hurt.fall.small");
        SoundRemapper.registerSoundRemapping("entity.player.small_fall", "game.player.hurt.fall.small");
        SoundRemapper.registerSoundRemapping("entity.generic.small_fall", "game.neutral.hurt.fall.small");
        SoundRemapper.register1_9Sound("ambient.cave");
        SoundRemapper.register1_9Sound("block.anvil.break");
        SoundRemapper.register1_9Sound("block.anvil.destroy");
        SoundRemapper.register1_9Sound("block.anvil.fall");
        SoundRemapper.register1_9Sound("block.anvil.hit");
        SoundRemapper.register1_9Sound("block.anvil.land");
        SoundRemapper.register1_9Sound("block.anvil.place");
        SoundRemapper.register1_9Sound("block.anvil.step");
        SoundRemapper.register1_9Sound("block.anvil.use");
        SoundRemapper.register1_9Sound("block.brewing_stand.brew");
        SoundRemapper.register1_9Sound("block.chest.close");
        SoundRemapper.register1_9Sound("block.chest.locked");
        SoundRemapper.register1_9Sound("block.chest.open");
        SoundRemapper.register1_9Sound("block.chorus_flower.death");
        SoundRemapper.register1_9Sound("block.chorus_flower.grow");
        SoundRemapper.register1_9Sound("block.cloth.break");
        SoundRemapper.register1_9Sound("block.cloth.fall");
        SoundRemapper.register1_9Sound("block.cloth.hit");
        SoundRemapper.register1_9Sound("block.cloth.place");
        SoundRemapper.register1_9Sound("block.cloth.step");
        SoundRemapper.register1_9Sound("block.comparator.click");
        SoundRemapper.register1_9Sound("block.dispenser.dispense");
        SoundRemapper.register1_9Sound("block.dispenser.fail");
        SoundRemapper.register1_9Sound("block.dispenser.launch");
        SoundRemapper.register1_9Sound("block.end_gateway.spawn");
        SoundRemapper.register1_9Sound("block.enderchest.close");
        SoundRemapper.register1_9Sound("block.enderchest.open");
        SoundRemapper.register1_9Sound("block.fence_gate.close");
        SoundRemapper.register1_9Sound("block.fence_gate.open");
        SoundRemapper.register1_9Sound("block.fire.ambient");
        SoundRemapper.register1_9Sound("block.fire.extinguish");
        SoundRemapper.register1_9Sound("block.furnace.fire_crackle");
        SoundRemapper.register1_9Sound("block.glass.break");
        SoundRemapper.register1_9Sound("block.glass.fall");
        SoundRemapper.register1_9Sound("block.glass.hit");
        SoundRemapper.register1_9Sound("block.glass.place");
        SoundRemapper.register1_9Sound("block.glass.step");
        SoundRemapper.register1_9Sound("block.grass.break");
        SoundRemapper.register1_9Sound("block.grass.fall");
        SoundRemapper.register1_9Sound("block.grass.hit");
        SoundRemapper.register1_9Sound("block.grass.place");
        SoundRemapper.register1_9Sound("block.grass.step");
        SoundRemapper.register1_9Sound("block.gravel.break");
        SoundRemapper.register1_9Sound("block.gravel.fall");
        SoundRemapper.register1_9Sound("block.gravel.hit");
        SoundRemapper.register1_9Sound("block.gravel.place");
        SoundRemapper.register1_9Sound("block.gravel.step");
        SoundRemapper.register1_9Sound("block.iron_door.close");
        SoundRemapper.register1_9Sound("block.iron_door.open");
        SoundRemapper.register1_9Sound("block.iron_trapdoor.close");
        SoundRemapper.register1_9Sound("block.iron_trapdoor.open");
        SoundRemapper.register1_9Sound("block.ladder.break");
        SoundRemapper.register1_9Sound("block.ladder.fall");
        SoundRemapper.register1_9Sound("block.ladder.hit");
        SoundRemapper.register1_9Sound("block.ladder.place");
        SoundRemapper.register1_9Sound("block.ladder.step");
        SoundRemapper.register1_9Sound("block.lava.ambient");
        SoundRemapper.register1_9Sound("block.lava.extinguish");
        SoundRemapper.register1_9Sound("block.lava.pop");
        SoundRemapper.register1_9Sound("block.lever.click");
        SoundRemapper.register1_9Sound("block.metal.break");
        SoundRemapper.register1_9Sound("block.metal.fall");
        SoundRemapper.register1_9Sound("block.metal.hit");
        SoundRemapper.register1_9Sound("block.metal.place");
        SoundRemapper.register1_9Sound("block.metal.step");
        SoundRemapper.register1_9Sound("block.metal_pressureplate.click_off");
        SoundRemapper.register1_9Sound("block.metal_pressureplate.click_on");
        SoundRemapper.register1_9Sound("block.note.basedrum");
        SoundRemapper.register1_9Sound("block.note.bass");
        SoundRemapper.register1_9Sound("block.note.harp");
        SoundRemapper.register1_9Sound("block.note.hat");
        SoundRemapper.register1_9Sound("block.note.pling");
        SoundRemapper.register1_9Sound("block.note.snare");
        SoundRemapper.register1_9Sound("block.piston.contract");
        SoundRemapper.register1_9Sound("block.piston.extend");
        SoundRemapper.register1_9Sound("block.portal.ambient");
        SoundRemapper.register1_9Sound("block.portal.travel");
        SoundRemapper.register1_9Sound("block.portal.trigger");
        SoundRemapper.register1_9Sound("block.redstone_torch.burnout");
        SoundRemapper.register1_9Sound("block.sand.break");
        SoundRemapper.register1_9Sound("block.sand.fall");
        SoundRemapper.register1_9Sound("block.sand.hit");
        SoundRemapper.register1_9Sound("block.sand.place");
        SoundRemapper.register1_9Sound("block.sand.step");
        SoundRemapper.register1_9Sound("block.slime.break");
        SoundRemapper.register1_9Sound("block.slime.fall");
        SoundRemapper.register1_9Sound("block.slime.hit");
        SoundRemapper.register1_9Sound("block.slime.place");
        SoundRemapper.register1_9Sound("block.slime.step");
        SoundRemapper.register1_9Sound("block.snow.break");
        SoundRemapper.register1_9Sound("block.snow.fall");
        SoundRemapper.register1_9Sound("block.snow.hit");
        SoundRemapper.register1_9Sound("block.snow.place");
        SoundRemapper.register1_9Sound("block.snow.step");
        SoundRemapper.register1_9Sound("block.stone.break");
        SoundRemapper.register1_9Sound("block.stone.fall");
        SoundRemapper.register1_9Sound("block.stone.hit");
        SoundRemapper.register1_9Sound("block.stone.place");
        SoundRemapper.register1_9Sound("block.stone.step");
        SoundRemapper.register1_9Sound("block.stone_button.click_off");
        SoundRemapper.register1_9Sound("block.stone_button.click_on");
        SoundRemapper.register1_9Sound("block.stone_pressureplate.click_off");
        SoundRemapper.register1_9Sound("block.stone_pressureplate.click_on");
        SoundRemapper.register1_9Sound("block.tripwire.attach");
        SoundRemapper.register1_9Sound("block.tripwire.click_off");
        SoundRemapper.register1_9Sound("block.tripwire.click_on");
        SoundRemapper.register1_9Sound("block.tripwire.detach");
        SoundRemapper.register1_9Sound("block.water.ambient");
        SoundRemapper.register1_9Sound("block.waterlily.place");
        SoundRemapper.register1_9Sound("block.wood.break");
        SoundRemapper.register1_9Sound("block.wood.fall");
        SoundRemapper.register1_9Sound("block.wood.hit");
        SoundRemapper.register1_9Sound("block.wood.place");
        SoundRemapper.register1_9Sound("block.wood.step");
        SoundRemapper.register1_9Sound("block.wood_button.click_off");
        SoundRemapper.register1_9Sound("block.wood_button.click_on");
        SoundRemapper.register1_9Sound("block.wood_pressureplate.click_off");
        SoundRemapper.register1_9Sound("block.wood_pressureplate.click_on");
        SoundRemapper.register1_9Sound("block.wooden_door.close");
        SoundRemapper.register1_9Sound("block.wooden_door.open");
        SoundRemapper.register1_9Sound("block.wooden_trapdoor.close");
        SoundRemapper.register1_9Sound("block.wooden_trapdoor.open");
        SoundRemapper.register1_9Sound("enchant.thorns.hit");
        SoundRemapper.register1_9Sound("entity.armorstand.break");
        SoundRemapper.register1_9Sound("entity.armorstand.fall");
        SoundRemapper.register1_9Sound("entity.armorstand.hit");
        SoundRemapper.register1_9Sound("entity.armorstand.place");
        SoundRemapper.register1_9Sound("entity.arrow.hit");
        SoundRemapper.register1_9Sound("entity.arrow.hit_player");
        SoundRemapper.register1_9Sound("entity.arrow.shoot");
        SoundRemapper.register1_9Sound("entity.bat.ambient");
        SoundRemapper.register1_9Sound("entity.bat.death");
        SoundRemapper.register1_9Sound("entity.bat.hurt");
        SoundRemapper.register1_9Sound("entity.bat.loop");
        SoundRemapper.register1_9Sound("entity.bat.takeoff");
        SoundRemapper.register1_9Sound("entity.blaze.ambient");
        SoundRemapper.register1_9Sound("entity.blaze.burn");
        SoundRemapper.register1_9Sound("entity.blaze.death");
        SoundRemapper.register1_9Sound("entity.blaze.hurt");
        SoundRemapper.register1_9Sound("entity.blaze.shoot");
        SoundRemapper.register1_9Sound("entity.bobber.splash");
        SoundRemapper.register1_9Sound("entity.bobber.throw");
        SoundRemapper.register1_9Sound("entity.cat.ambient");
        SoundRemapper.register1_9Sound("entity.cat.death");
        SoundRemapper.register1_9Sound("entity.cat.hiss");
        SoundRemapper.register1_9Sound("entity.cat.hurt");
        SoundRemapper.register1_9Sound("entity.cat.purr");
        SoundRemapper.register1_9Sound("entity.cat.purreow");
        SoundRemapper.register1_9Sound("entity.chicken.ambient");
        SoundRemapper.register1_9Sound("entity.chicken.death");
        SoundRemapper.register1_9Sound("entity.chicken.egg");
        SoundRemapper.register1_9Sound("entity.chicken.hurt");
        SoundRemapper.register1_9Sound("entity.chicken.step");
        SoundRemapper.register1_9Sound("entity.cow.ambient");
        SoundRemapper.register1_9Sound("entity.cow.death");
        SoundRemapper.register1_9Sound("entity.cow.hurt");
        SoundRemapper.register1_9Sound("entity.cow.milk");
        SoundRemapper.register1_9Sound("entity.cow.step");
        SoundRemapper.register1_9Sound("entity.creeper.death");
        SoundRemapper.register1_9Sound("entity.creeper.hurt");
        SoundRemapper.register1_9Sound("entity.creeper.primed");
        SoundRemapper.register1_9Sound("entity.donkey.ambient");
        SoundRemapper.register1_9Sound("entity.donkey.angry");
        SoundRemapper.register1_9Sound("entity.donkey.chest");
        SoundRemapper.register1_9Sound("entity.donkey.death");
        SoundRemapper.register1_9Sound("entity.donkey.hurt");
        SoundRemapper.register1_9Sound("entity.egg.throw");
        SoundRemapper.register1_9Sound("entity.elder_guardian.ambient");
        SoundRemapper.register1_9Sound("entity.elder_guardian.ambient_land");
        SoundRemapper.register1_9Sound("entity.elder_guardian.curse");
        SoundRemapper.register1_9Sound("entity.elder_guardian.death");
        SoundRemapper.register1_9Sound("entity.elder_guardian.death_land");
        SoundRemapper.register1_9Sound("entity.elder_guardian.hurt");
        SoundRemapper.register1_9Sound("entity.elder_guardian.hurt_land");
        SoundRemapper.register1_9Sound("entity.enderdragon.ambient");
        SoundRemapper.register1_9Sound("entity.enderdragon.death");
        SoundRemapper.register1_9Sound("entity.enderdragon.flap");
        SoundRemapper.register1_9Sound("entity.enderdragon.growl");
        SoundRemapper.register1_9Sound("entity.enderdragon.hurt");
        SoundRemapper.register1_9Sound("entity.enderdragon.shoot");
        SoundRemapper.register1_9Sound("entity.enderdragon_fireball.explode");
        SoundRemapper.register1_9Sound("entity.endereye.launch");
        SoundRemapper.register1_9Sound("entity.endermen.ambient");
        SoundRemapper.register1_9Sound("entity.endermen.death");
        SoundRemapper.register1_9Sound("entity.endermen.hurt");
        SoundRemapper.register1_9Sound("entity.endermen.scream");
        SoundRemapper.register1_9Sound("entity.endermen.stare");
        SoundRemapper.register1_9Sound("entity.endermen.teleport");
        SoundRemapper.register1_9Sound("entity.endermite.ambient");
        SoundRemapper.register1_9Sound("entity.endermite.death");
        SoundRemapper.register1_9Sound("entity.endermite.hurt");
        SoundRemapper.register1_9Sound("entity.endermite.step");
        SoundRemapper.register1_9Sound("entity.enderpearl.throw");
        SoundRemapper.register1_9Sound("entity.experience_bottle.throw");
        SoundRemapper.register1_9Sound("entity.experience_orb.pickup");
        SoundRemapper.register1_9Sound("entity.experience_orb.touch");
        SoundRemapper.register1_9Sound("entity.firework.blast");
        SoundRemapper.register1_9Sound("entity.firework.blast_far");
        SoundRemapper.register1_9Sound("entity.firework.large_blast");
        SoundRemapper.register1_9Sound("entity.firework.large_blast_far");
        SoundRemapper.register1_9Sound("entity.firework.launch");
        SoundRemapper.register1_9Sound("entity.firework.shoot");
        SoundRemapper.register1_9Sound("entity.firework.twinkle");
        SoundRemapper.register1_9Sound("entity.firework.twinkle_far");
        SoundRemapper.register1_9Sound("entity.generic.big_fall");
        SoundRemapper.register1_9Sound("entity.generic.burn");
        SoundRemapper.register1_9Sound("entity.generic.death");
        SoundRemapper.register1_9Sound("entity.generic.drink");
        SoundRemapper.register1_9Sound("entity.generic.eat");
        SoundRemapper.register1_9Sound("entity.generic.explode");
        SoundRemapper.register1_9Sound("entity.generic.extinguish_fire");
        SoundRemapper.register1_9Sound("entity.generic.hurt");
        SoundRemapper.register1_9Sound("entity.generic.small_fall");
        SoundRemapper.register1_9Sound("entity.generic.splash");
        SoundRemapper.register1_9Sound("entity.generic.swim");
        SoundRemapper.register1_9Sound("entity.ghast.ambient");
        SoundRemapper.register1_9Sound("entity.ghast.death");
        SoundRemapper.register1_9Sound("entity.ghast.hurt");
        SoundRemapper.register1_9Sound("entity.ghast.scream");
        SoundRemapper.register1_9Sound("entity.ghast.shoot");
        SoundRemapper.register1_9Sound("entity.ghast.warn");
        SoundRemapper.register1_9Sound("entity.guardian.ambient");
        SoundRemapper.register1_9Sound("entity.guardian.ambient_land");
        SoundRemapper.register1_9Sound("entity.guardian.attack");
        SoundRemapper.register1_9Sound("entity.guardian.death");
        SoundRemapper.register1_9Sound("entity.guardian.death_land");
        SoundRemapper.register1_9Sound("entity.guardian.flop");
        SoundRemapper.register1_9Sound("entity.guardian.hurt");
        SoundRemapper.register1_9Sound("entity.guardian.hurt_land");
        SoundRemapper.register1_9Sound("entity.horse.ambient");
        SoundRemapper.register1_9Sound("entity.horse.angry");
        SoundRemapper.register1_9Sound("entity.horse.armor");
        SoundRemapper.register1_9Sound("entity.horse.breathe");
        SoundRemapper.register1_9Sound("entity.horse.death");
        SoundRemapper.register1_9Sound("entity.horse.eat");
        SoundRemapper.register1_9Sound("entity.horse.gallop");
        SoundRemapper.register1_9Sound("entity.horse.hurt");
        SoundRemapper.register1_9Sound("entity.horse.jump");
        SoundRemapper.register1_9Sound("entity.horse.land");
        SoundRemapper.register1_9Sound("entity.horse.saddle");
        SoundRemapper.register1_9Sound("entity.horse.step");
        SoundRemapper.register1_9Sound("entity.horse.step_wood");
        SoundRemapper.register1_9Sound("entity.hostile.big_fall");
        SoundRemapper.register1_9Sound("entity.hostile.death");
        SoundRemapper.register1_9Sound("entity.hostile.hurt");
        SoundRemapper.register1_9Sound("entity.hostile.small_fall");
        SoundRemapper.register1_9Sound("entity.hostile.splash");
        SoundRemapper.register1_9Sound("entity.hostile.swim");
        SoundRemapper.register1_9Sound("entity.irongolem.attack");
        SoundRemapper.register1_9Sound("entity.irongolem.death");
        SoundRemapper.register1_9Sound("entity.irongolem.hurt");
        SoundRemapper.register1_9Sound("entity.irongolem.step");
        SoundRemapper.register1_9Sound("entity.item.break");
        SoundRemapper.register1_9Sound("entity.item.pickup");
        SoundRemapper.register1_9Sound("entity.itemframe.add_item");
        SoundRemapper.register1_9Sound("entity.itemframe.break");
        SoundRemapper.register1_9Sound("entity.itemframe.place");
        SoundRemapper.register1_9Sound("entity.itemframe.remove_item");
        SoundRemapper.register1_9Sound("entity.itemframe.rotate_item");
        SoundRemapper.register1_9Sound("entity.leashknot.break");
        SoundRemapper.register1_9Sound("entity.leashknot.place");
        SoundRemapper.register1_9Sound("entity.lightning.impact");
        SoundRemapper.register1_9Sound("entity.lightning.thunder");
        SoundRemapper.register1_9Sound("entity.lingeringpotion.throw");
        SoundRemapper.register1_9Sound("entity.magmacube.death");
        SoundRemapper.register1_9Sound("entity.magmacube.hurt");
        SoundRemapper.register1_9Sound("entity.magmacube.jump");
        SoundRemapper.register1_9Sound("entity.magmacube.squish");
        SoundRemapper.register1_9Sound("entity.minecart.inside");
        SoundRemapper.register1_9Sound("entity.minecart.riding");
        SoundRemapper.register1_9Sound("entity.mooshroom.shear");
        SoundRemapper.register1_9Sound("entity.mule.ambient");
        SoundRemapper.register1_9Sound("entity.mule.death");
        SoundRemapper.register1_9Sound("entity.mule.hurt");
        SoundRemapper.register1_9Sound("entity.painting.break");
        SoundRemapper.register1_9Sound("entity.painting.place");
        SoundRemapper.register1_9Sound("entity.pig.ambient");
        SoundRemapper.register1_9Sound("entity.pig.death");
        SoundRemapper.register1_9Sound("entity.pig.hurt");
        SoundRemapper.register1_9Sound("entity.pig.saddle");
        SoundRemapper.register1_9Sound("entity.pig.step");
        SoundRemapper.register1_9Sound("entity.player.attack.crit");
        SoundRemapper.register1_9Sound("entity.player.attack.knockback");
        SoundRemapper.register1_9Sound("entity.player.attack.nodamage");
        SoundRemapper.register1_9Sound("entity.player.attack.strong");
        SoundRemapper.register1_9Sound("entity.player.attack.sweep");
        SoundRemapper.register1_9Sound("entity.player.attack.weak");
        SoundRemapper.register1_9Sound("entity.player.big_fall");
        SoundRemapper.register1_9Sound("entity.player.breath");
        SoundRemapper.register1_9Sound("entity.player.burp");
        SoundRemapper.register1_9Sound("entity.player.death");
        SoundRemapper.register1_9Sound("entity.player.hurt");
        SoundRemapper.register1_9Sound("entity.player.levelup");
        SoundRemapper.register1_9Sound("entity.player.small_fall");
        SoundRemapper.register1_9Sound("entity.player.splash");
        SoundRemapper.register1_9Sound("entity.player.swim");
        SoundRemapper.register1_9Sound("entity.rabbit.ambient");
        SoundRemapper.register1_9Sound("entity.rabbit.attack");
        SoundRemapper.register1_9Sound("entity.rabbit.death");
        SoundRemapper.register1_9Sound("entity.rabbit.hurt");
        SoundRemapper.register1_9Sound("entity.rabbit.jump");
        SoundRemapper.register1_9Sound("entity.sheep.ambient");
        SoundRemapper.register1_9Sound("entity.sheep.death");
        SoundRemapper.register1_9Sound("entity.sheep.hurt");
        SoundRemapper.register1_9Sound("entity.sheep.shear");
        SoundRemapper.register1_9Sound("entity.sheep.step");
        SoundRemapper.register1_9Sound("entity.shulker.ambient");
        SoundRemapper.register1_9Sound("entity.shulker.close");
        SoundRemapper.register1_9Sound("entity.shulker.death");
        SoundRemapper.register1_9Sound("entity.shulker.hurt");
        SoundRemapper.register1_9Sound("entity.shulker.hurt_closed");
        SoundRemapper.register1_9Sound("entity.shulker.open");
        SoundRemapper.register1_9Sound("entity.shulker.shoot");
        SoundRemapper.register1_9Sound("entity.shulker.teleport");
        SoundRemapper.register1_9Sound("entity.shulker_bullet.hit");
        SoundRemapper.register1_9Sound("entity.shulker_bullet.hurt");
        SoundRemapper.register1_9Sound("entity.silverfish.ambient");
        SoundRemapper.register1_9Sound("entity.silverfish.death");
        SoundRemapper.register1_9Sound("entity.silverfish.hurt");
        SoundRemapper.register1_9Sound("entity.silverfish.step");
        SoundRemapper.register1_9Sound("entity.skeleton.ambient");
        SoundRemapper.register1_9Sound("entity.skeleton.death");
        SoundRemapper.register1_9Sound("entity.skeleton.hurt");
        SoundRemapper.register1_9Sound("entity.skeleton.shoot");
        SoundRemapper.register1_9Sound("entity.skeleton.step");
        SoundRemapper.register1_9Sound("entity.skeleton_horse.ambient");
        SoundRemapper.register1_9Sound("entity.skeleton_horse.death");
        SoundRemapper.register1_9Sound("entity.skeleton_horse.hurt");
        SoundRemapper.register1_9Sound("entity.slime.attack");
        SoundRemapper.register1_9Sound("entity.slime.death");
        SoundRemapper.register1_9Sound("entity.slime.hurt");
        SoundRemapper.register1_9Sound("entity.slime.jump");
        SoundRemapper.register1_9Sound("entity.slime.squish");
        SoundRemapper.register1_9Sound("entity.small_magmacube.death");
        SoundRemapper.register1_9Sound("entity.small_magmacube.hurt");
        SoundRemapper.register1_9Sound("entity.small_magmacube.squish");
        SoundRemapper.register1_9Sound("entity.small_slime.death");
        SoundRemapper.register1_9Sound("entity.small_slime.hurt");
        SoundRemapper.register1_9Sound("entity.small_slime.jump");
        SoundRemapper.register1_9Sound("entity.small_slime.squish");
        SoundRemapper.register1_9Sound("entity.snowball.throw");
        SoundRemapper.register1_9Sound("entity.snowman.ambient");
        SoundRemapper.register1_9Sound("entity.snowman.death");
        SoundRemapper.register1_9Sound("entity.snowman.hurt");
        SoundRemapper.register1_9Sound("entity.snowman.shoot");
        SoundRemapper.register1_9Sound("entity.spider.ambient");
        SoundRemapper.register1_9Sound("entity.spider.death");
        SoundRemapper.register1_9Sound("entity.spider.hurt");
        SoundRemapper.register1_9Sound("entity.spider.step");
        SoundRemapper.register1_9Sound("entity.splash_potion.break");
        SoundRemapper.register1_9Sound("entity.splash_potion.throw");
        SoundRemapper.register1_9Sound("entity.squid.ambient");
        SoundRemapper.register1_9Sound("entity.squid.death");
        SoundRemapper.register1_9Sound("entity.squid.hurt");
        SoundRemapper.register1_9Sound("entity.tnt.primed");
        SoundRemapper.register1_9Sound("entity.villager.ambient");
        SoundRemapper.register1_9Sound("entity.villager.death");
        SoundRemapper.register1_9Sound("entity.villager.hurt");
        SoundRemapper.register1_9Sound("entity.villager.no");
        SoundRemapper.register1_9Sound("entity.villager.trading");
        SoundRemapper.register1_9Sound("entity.villager.yes");
        SoundRemapper.register1_9Sound("entity.witch.ambient");
        SoundRemapper.register1_9Sound("entity.witch.death");
        SoundRemapper.register1_9Sound("entity.witch.drink");
        SoundRemapper.register1_9Sound("entity.witch.hurt");
        SoundRemapper.register1_9Sound("entity.witch.throw");
        SoundRemapper.register1_9Sound("entity.wither.ambient");
        SoundRemapper.register1_9Sound("entity.wither.break_block");
        SoundRemapper.register1_9Sound("entity.wither.death");
        SoundRemapper.register1_9Sound("entity.wither.hurt");
        SoundRemapper.register1_9Sound("entity.wither.shoot");
        SoundRemapper.register1_9Sound("entity.wither.spawn");
        SoundRemapper.register1_9Sound("entity.wolf.ambient");
        SoundRemapper.register1_9Sound("entity.wolf.death");
        SoundRemapper.register1_9Sound("entity.wolf.growl");
        SoundRemapper.register1_9Sound("entity.wolf.howl");
        SoundRemapper.register1_9Sound("entity.wolf.hurt");
        SoundRemapper.register1_9Sound("entity.wolf.pant");
        SoundRemapper.register1_9Sound("entity.wolf.shake");
        SoundRemapper.register1_9Sound("entity.wolf.step");
        SoundRemapper.register1_9Sound("entity.wolf.whine");
        SoundRemapper.register1_9Sound("entity.zombie.ambient");
        SoundRemapper.register1_9Sound("entity.zombie.attack_door_wood");
        SoundRemapper.register1_9Sound("entity.zombie.attack_iron_door");
        SoundRemapper.register1_9Sound("entity.zombie.break_door_wood");
        SoundRemapper.register1_9Sound("entity.zombie.death");
        SoundRemapper.register1_9Sound("entity.zombie.hurt");
        SoundRemapper.register1_9Sound("entity.zombie.infect");
        SoundRemapper.register1_9Sound("entity.zombie.step");
        SoundRemapper.register1_9Sound("entity.zombie_horse.ambient");
        SoundRemapper.register1_9Sound("entity.zombie_horse.death");
        SoundRemapper.register1_9Sound("entity.zombie_horse.hurt");
        SoundRemapper.register1_9Sound("entity.zombie_pig.ambient");
        SoundRemapper.register1_9Sound("entity.zombie_pig.angry");
        SoundRemapper.register1_9Sound("entity.zombie_pig.death");
        SoundRemapper.register1_9Sound("entity.zombie_pig.hurt");
        SoundRemapper.register1_9Sound("entity.zombie_villager.ambient");
        SoundRemapper.register1_9Sound("entity.zombie_villager.converted");
        SoundRemapper.register1_9Sound("entity.zombie_villager.cure");
        SoundRemapper.register1_9Sound("entity.zombie_villager.death");
        SoundRemapper.register1_9Sound("entity.zombie_villager.hurt");
        SoundRemapper.register1_9Sound("entity.zombie_villager.step");
        SoundRemapper.register1_9Sound("item.armor.equip_chain");
        SoundRemapper.register1_9Sound("item.armor.equip_diamond");
        SoundRemapper.register1_9Sound("item.armor.equip_generic");
        SoundRemapper.register1_9Sound("item.armor.equip_gold");
        SoundRemapper.register1_9Sound("item.armor.equip_iron");
        SoundRemapper.register1_9Sound("item.armor.equip_leather");
        SoundRemapper.register1_9Sound("item.bottle.fill");
        SoundRemapper.register1_9Sound("item.bottle.fill_dragonbreath");
        SoundRemapper.register1_9Sound("item.bucket.empty");
        SoundRemapper.register1_9Sound("item.bucket.empty_lava");
        SoundRemapper.register1_9Sound("item.bucket.fill");
        SoundRemapper.register1_9Sound("item.bucket.fill_lava");
        SoundRemapper.register1_9Sound("item.chorus_fruit.teleport");
        SoundRemapper.register1_9Sound("item.firecharge.use");
        SoundRemapper.register1_9Sound("item.flintandsteel.use");
        SoundRemapper.register1_9Sound("item.hoe.till");
        SoundRemapper.register1_9Sound("item.shield.block");
        SoundRemapper.register1_9Sound("item.shield.break");
        SoundRemapper.register1_9Sound("item.shovel.flatten");
        SoundRemapper.register1_9Sound("music.creative");
        SoundRemapper.register1_9Sound("music.credits");
        SoundRemapper.register1_9Sound("music.dragon");
        SoundRemapper.register1_9Sound("music.end");
        SoundRemapper.register1_9Sound("music.game");
        SoundRemapper.register1_9Sound("music.menu");
        SoundRemapper.register1_9Sound("music.nether");
        SoundRemapper.register1_9Sound("record.11");
        SoundRemapper.register1_9Sound("record.13");
        SoundRemapper.register1_9Sound("record.blocks");
        SoundRemapper.register1_9Sound("record.cat");
        SoundRemapper.register1_9Sound("record.chirp");
        SoundRemapper.register1_9Sound("record.far");
        SoundRemapper.register1_9Sound("record.mall");
        SoundRemapper.register1_9Sound("record.mellohi");
        SoundRemapper.register1_9Sound("record.stal");
        SoundRemapper.register1_9Sound("record.strad");
        SoundRemapper.register1_9Sound("record.wait");
        SoundRemapper.register1_9Sound("record.ward");
        SoundRemapper.register1_9Sound("ui.button.click");
        SoundRemapper.register1_9Sound("weather.rain");
        SoundRemapper.register1_9Sound("weather.rain.above");
    }
}

