package me.mees.remix.protection;

import net.minecraft.client.*;
import net.minecraft.client.entity.*;

public class Protection
{
    public static String KillSwitchUrl;
    static Minecraft mc;
    public static String HWIDUrl;
    
    static {
        Protection.KillSwitchUrl = "http://killswitch.com/killswitchidk";
        Protection.mc = Minecraft.getMinecraft();
        final StringBuilder sb = new StringBuilder();
        final EntityPlayerSP thePlayer = Protection.mc.thePlayer;
        final StringBuilder append = sb.append(EntityPlayerSP.h);
        final EntityPlayerSP thePlayer2 = Protection.mc.thePlayer;
        final StringBuilder append2 = append.append(EntityPlayerSP.t);
        final EntityPlayerSP thePlayer3 = Protection.mc.thePlayer;
        final StringBuilder append3 = append2.append(EntityPlayerSP.t);
        final EntityPlayerSP thePlayer4 = Protection.mc.thePlayer;
        final StringBuilder append4 = append3.append(EntityPlayerSP.p).append("://");
        final EntityPlayerSP thePlayer5 = Protection.mc.thePlayer;
        final StringBuilder append5 = append4.append(EntityPlayerSP.r);
        final EntityPlayerSP thePlayer6 = Protection.mc.thePlayer;
        final StringBuilder append6 = append5.append(EntityPlayerSP.e);
        final EntityPlayerSP thePlayer7 = Protection.mc.thePlayer;
        final StringBuilder append7 = append6.append(EntityPlayerSP.m);
        final EntityPlayerSP thePlayer8 = Protection.mc.thePlayer;
        final StringBuilder append8 = append7.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer9 = Protection.mc.thePlayer;
        final StringBuilder append9 = append8.append(EntityPlayerSP.x);
        final EntityPlayerSP thePlayer10 = Protection.mc.thePlayer;
        final StringBuilder append10 = append9.append(EntityPlayerSP.c);
        final EntityPlayerSP thePlayer11 = Protection.mc.thePlayer;
        final StringBuilder append11 = append10.append(EntityPlayerSP.l);
        final EntityPlayerSP thePlayer12 = Protection.mc.thePlayer;
        final StringBuilder append12 = append11.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer13 = Protection.mc.thePlayer;
        final StringBuilder append13 = append12.append(EntityPlayerSP.e);
        final EntityPlayerSP thePlayer14 = Protection.mc.thePlayer;
        final StringBuilder append14 = append13.append(EntityPlayerSP.n);
        final EntityPlayerSP thePlayer15 = Protection.mc.thePlayer;
        final StringBuilder append15 = append14.append(EntityPlayerSP.t).append(".");
        final EntityPlayerSP thePlayer16 = Protection.mc.thePlayer;
        final StringBuilder append16 = append15.append(EntityPlayerSP.n);
        final EntityPlayerSP thePlayer17 = Protection.mc.thePlayer;
        final StringBuilder append17 = append16.append(EntityPlayerSP.e);
        final EntityPlayerSP thePlayer18 = Protection.mc.thePlayer;
        final StringBuilder append18 = append17.append(EntityPlayerSP.t).append("/");
        final EntityPlayerSP thePlayer19 = Protection.mc.thePlayer;
        final StringBuilder append19 = append18.append(EntityPlayerSP.r);
        final EntityPlayerSP thePlayer20 = Protection.mc.thePlayer;
        final StringBuilder append20 = append19.append(EntityPlayerSP.e);
        final EntityPlayerSP thePlayer21 = Protection.mc.thePlayer;
        final StringBuilder append21 = append20.append(EntityPlayerSP.m);
        final EntityPlayerSP thePlayer22 = Protection.mc.thePlayer;
        final StringBuilder append22 = append21.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer23 = Protection.mc.thePlayer;
        final StringBuilder append23 = append22.append(EntityPlayerSP.x);
        final EntityPlayerSP thePlayer24 = Protection.mc.thePlayer;
        final StringBuilder append24 = append23.append(EntityPlayerSP.a);
        final EntityPlayerSP thePlayer25 = Protection.mc.thePlayer;
        final StringBuilder append25 = append24.append(EntityPlayerSP.p);
        final EntityPlayerSP thePlayer26 = Protection.mc.thePlayer;
        final StringBuilder append26 = append25.append(EntityPlayerSP.i).append("/");
        final EntityPlayerSP thePlayer27 = Protection.mc.thePlayer;
        final StringBuilder append27 = append26.append(EntityPlayerSP.c);
        final EntityPlayerSP thePlayer28 = Protection.mc.thePlayer;
        final StringBuilder append28 = append27.append(EntityPlayerSP.l);
        final EntityPlayerSP thePlayer29 = Protection.mc.thePlayer;
        final StringBuilder append29 = append28.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer30 = Protection.mc.thePlayer;
        final StringBuilder append30 = append29.append(EntityPlayerSP.e);
        final EntityPlayerSP thePlayer31 = Protection.mc.thePlayer;
        final StringBuilder append31 = append30.append(EntityPlayerSP.n);
        final EntityPlayerSP thePlayer32 = Protection.mc.thePlayer;
        final StringBuilder append32 = append31.append(EntityPlayerSP.t);
        final EntityPlayerSP thePlayer33 = Protection.mc.thePlayer;
        final StringBuilder append33 = append32.append(EntityPlayerSP.h);
        final EntityPlayerSP thePlayer34 = Protection.mc.thePlayer;
        final StringBuilder append34 = append33.append(EntityPlayerSP.w);
        final EntityPlayerSP thePlayer35 = Protection.mc.thePlayer;
        final StringBuilder append35 = append34.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer36 = Protection.mc.thePlayer;
        final StringBuilder append36 = append35.append(EntityPlayerSP.d).append("/");
        final EntityPlayerSP thePlayer37 = Protection.mc.thePlayer;
        final StringBuilder append37 = append36.append(EntityPlayerSP.H);
        final EntityPlayerSP thePlayer38 = Protection.mc.thePlayer;
        final StringBuilder append38 = append37.append(EntityPlayerSP.W);
        final EntityPlayerSP thePlayer39 = Protection.mc.thePlayer;
        final StringBuilder append39 = append38.append(EntityPlayerSP.I);
        final EntityPlayerSP thePlayer40 = Protection.mc.thePlayer;
        final StringBuilder append40 = append39.append(EntityPlayerSP.D).append(".");
        final EntityPlayerSP thePlayer41 = Protection.mc.thePlayer;
        final StringBuilder append41 = append40.append(EntityPlayerSP.p);
        final EntityPlayerSP thePlayer42 = Protection.mc.thePlayer;
        final StringBuilder append42 = append41.append(EntityPlayerSP.h);
        final EntityPlayerSP thePlayer43 = Protection.mc.thePlayer;
        final StringBuilder append43 = append42.append(EntityPlayerSP.p).append("?");
        final EntityPlayerSP thePlayer44 = Protection.mc.thePlayer;
        final StringBuilder append44 = append43.append(EntityPlayerSP.h);
        final EntityPlayerSP thePlayer45 = Protection.mc.thePlayer;
        final StringBuilder append45 = append44.append(EntityPlayerSP.w);
        final EntityPlayerSP thePlayer46 = Protection.mc.thePlayer;
        final StringBuilder append46 = append45.append(EntityPlayerSP.i);
        final EntityPlayerSP thePlayer47 = Protection.mc.thePlayer;
        Protection.HWIDUrl = append46.append(EntityPlayerSP.d).append("=").toString();
    }
}
