package zamorozka.module;

import java.util.ArrayList;

import zamorozka.modules.COMBAT.*;
import zamorozka.modules.COMBAT.PearlNotifier;
import zamorozka.modules.EXPLOITS.*;
import zamorozka.modules.GUIMenu.*;
import zamorozka.modules.HUD.*;
import zamorozka.modules.PLAYER.*;
import zamorozka.modules.POTION.*;
import zamorozka.modules.TRAFFIC.*;
import zamorozka.modules.VISUALLY.*;
import zamorozka.modules.WORLD.*;
import zamorozka.modules.ZAMOROZKA.*;

public class ModuleManager {

	public static ArrayList<Module> activeModules = new ArrayList<Module>();
	public Xray xrayModule;

	public ModuleManager() {
		Xray xrayModule;
		this.activeModules.add(new FriendDamageCancel());
		this.activeModules.add(new Sprint());
		this.activeModules.add(new Fly());
		this.activeModules.add(new ClickGui());
		this.activeModules.add(new AntiFall());
		this.activeModules.add(new Jesus());
		this.activeModules.add(new Wallhack());
		this.activeModules.add(new ESP2());
		this.activeModules.add(new Esp());
		this.activeModules.add(new FullBright());
		this.activeModules.add(new ChestBox());
		this.activeModules.add(new BedEsp());
		this.activeModules.add(new ItemEsp());
		this.activeModules.add(new VehicleFly());
		this.activeModules.add(new BoatFly());
		this.activeModules.add(new XrauBiposs());
		this.activeModules.add(new ChestStealer());
		this.activeModules.add(new AntiFire());
		this.activeModules.add(new NoFall());
		this.activeModules.add(new Timer());
		this.activeModules.add(new FastPlace());
		this.activeModules.add(new FlyPoin());
		this.activeModules.add(new KillAura());
		this.activeModules.add(new AimBot());
		this.activeModules.add(new AutoTotem());
		this.activeModules.add(new Reach());
		this.activeModules.add(new NightVision());
		this.activeModules.add(this.xrayModule = new Xray());
		this.activeModules.add(new Criticals());
		this.activeModules.add(new FastBow());
		this.activeModules.add(new Spammer());
		this.activeModules.add(new AutoArmor());
		this.activeModules.add(new HitBox());
		this.activeModules.add(new Spider());
		this.activeModules.add(new NoSlow());
		this.activeModules.add(new AntiAim());
		this.activeModules.add(new HUD());
		this.activeModules.add(new CrashPacket());
		this.activeModules.add(new SafeWalk());
		this.activeModules.add(new Zamorozka1());
		this.activeModules.add(new NameTags());
		// this.activeModules.add(new HealthTag());
		this.activeModules.add(new AuthCrash());
		this.activeModules.add(new AntiAfk());
		this.activeModules.add(new ReachBlock());
		this.activeModules.add(new ElytraFly());
		this.activeModules.add(new NoWeb());
		this.activeModules.add(new Fucker());
		this.activeModules.add(new FastLadder());
		this.activeModules.add(new MCF());
		this.activeModules.add(new KeepSprint());
		this.activeModules.add(new NoClip());
		this.activeModules.add(new InventoryWalk());
		this.activeModules.add(new Chams());
		this.activeModules.add(new PearlCooldown());
		this.activeModules.add(new noname());
		this.activeModules.add(new SaveMod());
		this.activeModules.add(new BowAimBot());
		this.activeModules.add(new AntiPushoutoOfBlock());
		this.activeModules.add(new EnderChest());
		this.activeModules.add(new AutoClicker());
		this.activeModules.add(new Freecam());
		this.activeModules.add(new Crystalaura());
		this.activeModules.add(new ArreyList());
		this.activeModules.add(new Triggerbot());
		this.activeModules.add(new Logo());
		this.activeModules.add(new Click());
		this.activeModules.add(new NoScoreBoard());
		this.activeModules.add(new AutoPot());
		this.activeModules.add(new AutoSword());
		this.activeModules.add(new Parkour());
		this.activeModules.add(new Trajectories());
		this.activeModules.add(new AutoWaterBucket());
		this.activeModules.add(new SeeUnderLiquid());
		this.activeModules.add(new NoHurtCam());
		this.activeModules.add(new Eagle());
		this.activeModules.add(new NoJumpDelay());
		this.activeModules.add(new NoNausea());
		this.activeModules.add(new XrayLite());
		this.activeModules.add(new AntiCactus());
		this.activeModules.add(new AntiCollision());
		this.activeModules.add(new Terrain());
		this.activeModules.add(new TrueSight());
		this.activeModules.add(new AutoShiftTap());
		this.activeModules.add(new AutoRespawn());
		this.activeModules.add(new AutoTool());
		this.activeModules.add(new SeeBarriers());
		this.activeModules.add(new NoArrowSound());
		this.activeModules.add(new AutoClimb());
		this.activeModules.add(new Step());
		this.activeModules.add(new Tracers());
		this.activeModules.add(new CameraClip());
		this.activeModules.add(new ShieldESP());
		this.activeModules.add(new AutoGap());
		this.activeModules.add(new NoBlindEffect());
		this.activeModules.add(new NoRotateSet());
		this.activeModules.add(new FastFall());
		this.activeModules.add(new Clip());
		this.activeModules.add(new XCarry());
		this.activeModules.add(new BetterLevitation());
		this.activeModules.add(new VelocityPercentage());
		this.activeModules.add(new WorldTime());
		this.activeModules.add(new InviniteChatLength());
		this.activeModules.add(new MiddleClickPearl());
		this.activeModules.add(new AutoWalk());
		this.activeModules.add(new AntiHunger());
		this.activeModules.add(new PerfectHorseJump());
		this.activeModules.add(new AutomaticallyBreak());
		this.activeModules.add(new NoBlockHitDelay());
		this.activeModules.add(new AutoFish());
		this.activeModules.add(new BadPotionRemover());
		this.activeModules.add(new NoCameraSmooth());
		this.activeModules.add(new PortalChat());
		this.activeModules.add(new DeathCoords());
		this.activeModules.add(new AntiDesync());
		this.activeModules.add(new PortalGod());
		this.activeModules.add(new SpeedHack());
		this.activeModules.add(new Teleport());
		this.activeModules.add(new NoLag());
		this.activeModules.add(new NoMiningTrace());
		this.activeModules.add(new NoBuildLimit());
		this.activeModules.add(new AutoBreedAnimals());
		this.activeModules.add(new AutoSheepShearing());
		this.activeModules.add(new SmallShield());
		this.activeModules.add(new FastUse());
		this.activeModules.add(new ItemPhysic());
		this.activeModules.add(new EnchantColor());
		this.activeModules.add(new AirStuck());
		this.activeModules.add(new AutoJump());
		this.activeModules.add(new NoWalkAnimation());
		this.activeModules.add(new CustomJumpHeight());
		this.activeModules.add(new NoEntitySpawnPackets());
		this.activeModules.add(new PacketKickBypass());
		this.activeModules.add(new VillagerInteract());
		this.activeModules.add(new SkeletonESP());
		this.activeModules.add(new Crosshair());
		this.activeModules.add(new FastBreak());
		this.activeModules.add(new LiquidInteract());
		this.activeModules.add(new AutoFarm());
		this.activeModules.add(new Lawnmower());
		this.activeModules.add(new AntiSlowBreak());
		this.activeModules.add(new PacketFly());
		this.activeModules.add(new GhostHand());
		this.activeModules.add(new AutoShovelWay());
		this.activeModules.add(new SpawnParticles());
		this.activeModules.add(new LagCheck());
		this.activeModules.add(new AntiBot2());
		this.activeModules.add(new Radar());
		this.activeModules.add(new BlockOutline());
		this.activeModules.add(new YoutuberMode());
		this.activeModules.add(new WallSpeed());
		this.activeModules.add(new TargetStrafe());
		this.activeModules.add(new PacketXP());
		this.activeModules.add(new NoTitle());
		this.activeModules.add(new PingSpoof());
		this.activeModules.add(new TotemDetector());
		this.activeModules.add(new Phase());
		this.activeModules.add(new AutoGG());
		this.activeModules.add(new ShulkerViewer());
		this.activeModules.add(new AntiSlowness());
		this.activeModules.add(new KeyStrokes());
		this.activeModules.add(new AutoSneak());
		this.activeModules.add(new InvSorter());
		this.activeModules.add(new ShaderESP());
		this.activeModules.add(new LongJump());
		this.activeModules.add(new Scaffold());
		this.activeModules.add(new HeadOverHeels());
		this.activeModules.add(new Disabler());
		this.activeModules.add(new BlockEsp());
		this.activeModules.add(new Configs());
		this.activeModules.add(new FastEat());
		this.activeModules.add(new AutoShield());
		this.activeModules.add(new AntiTrap());
		this.activeModules.add(new AirBoost());
		this.activeModules.add(new AutoRune());
		this.activeModules.add(new DamageNotifi());
		this.activeModules.add(new SuperKnockBack());
		this.activeModules.add(new WaterLeave());
		this.activeModules.add(new Nuker());
		this.activeModules.add(new PearlNotifier());
		this.activeModules.add(new CustomHand());
		this.activeModules.add(new MemoryFix());
		this.activeModules.add(new CustomHitColor());
		this.activeModules.add(new AutoReg());
		this.activeModules.add(new Animations());
		this.activeModules.add(new Strafe());
		this.activeModules.add(new RadiusAntiBot());
		this.activeModules.add(new NoOverlay());
		this.activeModules.add(new Outline());
		this.activeModules.add(new FakeHack());
	}

	public static ArrayList<Module> getModules() {
		return activeModules;
	}

	public static Module getModule(Class<? extends Module> clazz) {
		for (Module mod : getModules()) {
			if (mod.getClass() == clazz) {
				return mod;
			}
		}
		return null;
	}
}